// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDLXp53MkvLik_7QmjjV5JimUeA7UFLZR0',
    appId: '1:868925072147:web:5dfeecfdb992a01acb30e6',
    messagingSenderId: '868925072147',
    projectId: 'semanacomputacaoapp',
    authDomain: 'semanacomputacaoapp.firebaseapp.com',
    storageBucket: 'semanacomputacaoapp.firebasestorage.app',
    measurementId: 'G-BXWLVS9YV3',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDpiYqf1yryleSyZ41hLFT9DJjANqh9U1Y',
    appId: '1:868925072147:android:26499bc8539f72c4cb30e6',
    messagingSenderId: '868925072147',
    projectId: 'semanacomputacaoapp',
    storageBucket: 'semanacomputacaoapp.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAOhc8xP2SBkYJ1ANhuKU04tAlbNCX2RfU',
    appId: '1:868925072147:ios:9867ee7c89110259cb30e6',
    messagingSenderId: '868925072147',
    projectId: 'semanacomputacaoapp',
    storageBucket: 'semanacomputacaoapp.firebasestorage.app',
    iosBundleId: 'com.example.flutterApplicationUfop',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAOhc8xP2SBkYJ1ANhuKU04tAlbNCX2RfU',
    appId: '1:868925072147:ios:9867ee7c89110259cb30e6',
    messagingSenderId: '868925072147',
    projectId: 'semanacomputacaoapp',
    storageBucket: 'semanacomputacaoapp.firebasestorage.app',
    iosBundleId: 'com.example.flutterApplicationUfop',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDLXp53MkvLik_7QmjjV5JimUeA7UFLZR0',
    appId: '1:868925072147:web:b92163d149dbbd0ccb30e6',
    messagingSenderId: '868925072147',
    projectId: 'semanacomputacaoapp',
    authDomain: 'semanacomputacaoapp.firebaseapp.com',
    storageBucket: 'semanacomputacaoapp.firebasestorage.app',
    measurementId: 'G-WCFXGX7KBV',
  );
}
